# Generated by Django 3.2.13 on 2022-05-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_iser',
            new_name='id_user',
        ),
    ]
