# Generated by Django 3.2.13 on 2022-05-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_of_like',
            new_name='no_of_likes',
        ),
    ]
